name: virbench
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python
  - bioconda::diamond>=2.0.10 # Requires >=2.0.10 for '--fast' sensitivity
  - bioconda::fastplong
  - bioconda::minimap2
  - bioconda::samtools
  - bioconda::flye
  - bioconda::plass
  - bioconda::seqkit
  - bioconda::quast
  - bioconda::bbmap
  - bioconda::checkv
  - bioconda::raven-assembler
  - bioconda::miniasm
  - bioconda::racon
  - bioconda::gfatools
  - bioconda::snakemake
  - bioconda::canu
  - bioconda::mmseqs2
  - bioconda::cutadapt
  - conda-forge::rsync
  - bioconda::seqtk
  - conda-forge::quarto
  - conda-forge::r-quarto
  - conda-forge::r-knitr
  - conda-forge::r-dplyr
  - conda-forge::r-readr
